language: node_js
node_js:
  - "node"
services:
  - postgresql
env:
  - PG_DB_CONNECTION_URL='postgres://postgres@localhost:5432/fast_food_fast_test'
before_script:
  - psql -c 'create database fast_food_fast_test;' -U postgres
script:
  - npm install
  - npm run test
after_success: 
  - npm run coveralls
cache:
  directories:
    - "node_modules"