language: node_js

node_js:
  - "8.11.3"

dist: trusty

services:
  - postgresql

env:
  global:
  - NODE_ENV=test

before_script:
  - psql -c 'create database fast-fast-test-db' -U postgres

script:
  - npm install
  - npm test

after_success: 
  - npm run coveralls

cache:
  directories:
    - "node_modules"